function install_mex()

src_files = {
    'mex_cutting_plane_mc.c', ...
    'mexfun_mex_almssn_compute_pgU.c', ...
    'mexfun_mex_almssn_compute_RpgU.c', ...
    'mex_maxcut_applyA.c', ...
    'mex_theta_applyA.c', ...
    'mex_theta_applyA_full.c', ...
    'mex_theta_applyAT.c'};

for i = 1:numel(src_files)
    mex(src_files{i}, '-O', '-largeArrayDims', '-lmwblas');
end

end