function names = R1TAprobs_big()
	names = { ...
		'nonsym(12,4)',...
		'nonsym(13,4)',...
		'nonsym(18,4)',...
		'nonsym(20,4)',...
		'nonsym(21,4)',...
		'nonsym(7,5)',...
		'nonsym(8,5)',...
	};

end