function [names, nlist] = rcpprobs_200()
    names = { ...
        'abalone', ...
        'housing', ...
        'segment', ...
         'soybean-large', ...
        'spambase', ...
    };

    nlist = {
        {{200, '-small'}, {400, '-medium'}, {1000, '-large'}}, ...
        {{506, ''}}, ...
        {{400, '-small'}, {700, '-medium'}, {1000, '-large'}}, ...
        {{307, ''}}, ...
        {{300, '-small'}, {900, '-medium'}, {1500, '-large'}}, ...
    };
end