function [names, nlist] = rcpprobs_small(small_type)
    switch small_type
        case 1
            names = { ...
                'abalone', ...
                'housing', ...
                'segment', ...
                 'soybean-large', ...
                 'soybean-small', ...
                'spambase', ...
            };

            nlist = {
                {{200, '-small'}, {400, '-medium'}}, ...
                {{506, ''}}, ...
                {{400, '-small'}, {700, '-medium'}}, ...
                {{307, ''}}, ...
                {{47, ''}}, ...
                {{300, '-small'}}, ...
            };
        case 2
            names = { ...
                'abalone', ...
            };

            nlist = {
                { {1000, '-large'}}, ...
            };
        case 3
            names = { ...
                'segment', ...
            };

            nlist = {
                { {1000, '-large'}}, ...
            };
        case 4
            names = { ...
                'spambase', ...
            };

            nlist = {
                {{900, '-medium'}}, ...
            };
    end
end
